akka {
  loglevel = warning
  actor {
    provider = cluster

    serialization-bindings {
      "cannon.cluster.CborSerializable" = jackson-cbor
    }
  }
  remote {
    artery {
      canonical.hostname = "127.0.0.1"
      canonical.port = 0
    }
  }
  cluster {
  seed-nodes = [
        "akka://NodeWorkerSystem@127.0.0.1:25251",
        "akka://NodeWorkerSystem@127.0.0.1:25252"]
    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
  }
}
